[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_ENV = "production", NEXT_TELEMETRY_DISABLED = "1" }

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
