[build]
  command = "NEXT_DISABLE_ESLINT=true npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.17.0"
  NEXT_TELEMETRY_DISABLED = "1"

[build.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache",
    ".eslintcache"
  ]

[[redirects]]
  from = "/*"
  to = "/"
  status = 200